#!/usr/bin/env python
#-*- mode:python -*-

import sys
import os

if not len(sys.argv) == 2:
    print "usage: %s <directory>" % sys.argv[0]
    sys.exit(-1)

dir = sys.argv[1]

cmd = '/home/mike/projects/photo/scripts/cleaner %s' % dir
print cmd
os.system(cmd)

cmd = '/home/mike/projects/photo/scripts/thumbnail %s' % dir
print cmd
os.system(cmd)

cmd = '/home/mike/projects/photo/scripts/small-ifier %s' % dir
print cmd
os.system(cmd)

cmd = '/home/mike/projects/photo/scripts/image-ifier %s' % dir
print cmd
os.system(cmd)

