#!/usr/bin/env python

import os
import sys
from PIL import Image
sys.path.insert(0,'/home/mike/projects/photo/src/')
from Node import Node, SPECIAL

def cmd(s):
    print s
    os.system(s)
    
for x in os.listdir('.'):
    if x[-3:].lower() == 'jpg':
        cmd("mv %s %s" % (x,x[:-3]+'jpeg'))
